### PR TITLE
add empty message for media picker

### PR DESCRIPTION
**Pull request by brandonmbanks**
image

### CODE REVIEW

**Comment by banks117** [comment]
Well @willdady, you sure made this easy.

This should close https://github.com/contentjet/contentjet-ui/issues/2.

**Comment by willdady** [comment]
Thanks @brandonmbanks! Instead of rendering the message in the left column lets not render the columns or search input at all and **only** show the alert. My thinking is the search input doesn't make sense being there if there is nothing to search for.

**Comment by banks117** [comment]
Makes sense to me. I can do that.

**Comment by banks117** [comment]
image

**Comment by banks117** [comment]
@willdady How does that look?

**Comment by banks117** [comment]
@willdady Hey man. Just pinging you to see if you think this looks good or want me to make any more changes.

**Comment by willdady** [comment]
Looks great! Thanks @brandonmbanks!

**Comment by banks117** [comment]
Happy to help man!

**Pull request merged**
